version: '3'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:Demo123@db:5432/postgresql
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      bash -c "alembic upgrade head && python app.py"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Demo123
      POSTGRES_DB: postgresql
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
