"""Create dialogue_record table.

Revision ID: 1624a28ee97c
Revises: 3ea958e0493d
Create Date: 2024-10-13 12:33:34.587884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1624a28ee97c'
down_revision: Union[str, None] = '3ea958e0493d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
