"""Testing Output

Revision ID: 1d19ffc6d6d1
Revises: 1624a28ee97c
Create Date: 2024-10-13 13:07:37.792188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d19ffc6d6d1'
down_revision: Union[str, None] = '1624a28ee97c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
